- name: Get start timestamp
  hosts: cloud
  connection: local
  become: true
  become_user: root
  tasks:
    - name: Get a build number
      set_fact:
        buildno: "{{ lookup('env', 'BUILD_NUMBER') }}"
    - name: Get nmon chart target directory
      set_fact:
        targetdir: "{{ ansible_date_time.date }}-{{ buildno }}"
    - name: Setup hyperledger directory
      file:
        path: "/var/www/html/{{ targetdir }}"
        state: directory

- name: Get start timestamp
  hosts: allnodes
  strategy: free
  user: "{{ user }}"
  become: true
  become_user: root
  tasks:
    - name: create nmonchart
      command: >-
        nmonchart /opt/{{ hostvars[inventory_hostname].inter_name }}.nmon
        /opt/{{ hostvars[inventory_hostname].inter_name }}.html

    - name: gather nmonchart
      fetch:
        src: "/opt/{{ hostvars[inventory_hostname].inter_name }}.html"
        dest: "/var/www/html/{{ hostvars['cloud'].targetdir }}"
