- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - name: Get a build number
      set_fact:
        buildno: "{{ lookup('env', 'BUILD_NUMBER') }}"
        jobname: "{{ lookup('env', 'JOB_NAME') }}" 
    - name: Get nmon chart target directory
      set_fact:
        targetdir: "{{ ansible_date_time.date }}-{{ jobname }}-{{ buildno }}"
    - name: Setup hyperledger directory
      file:
        path: "/var/www/html/reports/{{ targetdir }}"
        state: directory

- name: Get start timestamp
  hosts: allnodes
  strategy: free
  user: "{{ user }}"
  become: true
  become_user: root
  tasks:
    - name: stop the nmon daemon
      shell: kill -USR2 $(pidof nmon16g_x86_ubuntu1604)

    - name: combine the nmon chart files
      shell: cat /opt/{{ hostvars[inventory_hostname].inter_name }}.nmon /opt/udp.csv > /opt/data.nmon

    - name: create nmonchart
      command: >-
        nmonchart /opt/data.nmon
        /opt/{{ hostvars[inventory_hostname].inter_name }}.{{ jobname }}.html

    - name: gather nmonchart
      fetch:
        src: "/opt/{{ hostvars[inventory_hostname].inter_name }}.{{ jobname }}.html"
        dest: "/var/www/html/reports/{{ hostvars['cloud'].targetdir }}/"
        flat: yes
