- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - name: Get a build number
      set_fact:
        buildno: "{{ lookup('env', 'BUILD_NUMBER') }}"
    - name: Get nmon chart target directory
      set_fact:
        targetdir: "{{ ansible_date_time.date }}B{{ buildno }}"
    - name: Setup hyperledger directory
      file:
        path: "/var/www/html/reports/{{ targetdir }}"
        state: directory

- name: Get start timestamp
  hosts: allnodes
  strategy: free
  user: "{{ user }}"
  become: true
  become_user: root
  tasks:
    - name: combine the nmon chart files
      shell: cat /opt/{{ hostvars[inventory_hostname].inter_name }}.nmon udp.csv > /opt/data.nmon

    - name: create nmonchart
      command: >-
        nmonchart /opt/data.nmon
        /opt/{{ hostvars[inventory_hostname].inter_name }}.html

    - name: gather nmonchart
      fetch:
        src: "/opt/{{ hostvars[inventory_hostname].inter_name }}.html"
        dest: "/var/www/html/reports/{{ hostvars['cloud'].targetdir }}/"
        flat: yes
