- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - name: Get a build number
      set_fact:
        buildno: "{{ lookup('env', 'BUILD_NUMBER') }}"
    - name: Get nmon chart target directory
      set_fact:
        targetdir: "{{ ansible_date_time.date }}-{{ buildno }}"
    - name: Setup hyperledger directory
      file:
        path: "{{ targetdir }}"
        state: directory

- name: Get start timestamp
  hosts: allnodes
  strategy: free
  user: "{{ user }}"
  become: true
  become_user: root
  tasks:
    - name: Unpack nmon binary
      unarchive:
        src: "https://ayera.dl.sourceforge.net/project/nmon/nmon16g_x86.tar.gz"
        dest: "/usr/local/bin"
        exclude:
          - nmon16g_x86_sles114
          - nmon16g_x86_sles12
          - nmon16g_x86_fedora25
          - nmon16g_x86_rhel72
        copy: no
        mode: +x

    - name: Install packages
      apt:
        name: ksh

    - name: Unpack nmonchart binary
      unarchive:
        src: "https://gigenet.dl.sourceforge.net/project/nmon/nmonchart33.tar"
        dest: "/usr/local/bin"
        exclude:
          - README
          - nmon_upload.html
          - nmon_upload.php
          - nmonchart_cron
          - nmonchart_license
          - sampleC.html
          - sampleC.nmon
          - sampleD.html
          - sampleD.nmon
        copy: no
        mode: +x

    - name: Start nmon
      command: "nmon16g_x86_ubuntu1604 -fT -s 30 -m /opt -F {{ hostvars[inventory_hostname].inter_name }}.nmon"
