netbc1st:
  - command: "tool_type=pte pteenv=2channels chaincode=samplejs testcase=FAB-7246-4i"
    skip_tags: "code,make,cleanfabric"
  - command: "tool_type=pte pteenv=8channels chaincode=samplecc testcase=FAB-7627-16q"
    skip_tags: "code,make,cleanfabric"
