netbc1st:
  - name: "FAB-7246-4i"
    extra: "tool_type=pte pteenv=2channels chaincode=samplejs testcase=FAB-7246-4i"
    skip_tags: "code,make,cleanfabric"
  - name: "FAB-7627-16q"
    extra: "tool_type=pte pteenv=8channels chaincode=samplecc testcase=FAB-7627-16q"
    skip_tags: "code,make,cleanfabric"
